/**
 * aegisFlasher Microcontroller Board Pinout Catalog & Interactive Diagrams
 */

import { BoardPinoutProfile } from "./types";

export const BOARD_PINOUTS: BoardPinoutProfile[] = [
  // 1. ESP32 30-Pin DevKit
  {
    id: "esp32-devkit-30",
    name: "ESP32 DevKit V1 (30-Pin WROOM-32)",
    chip: "ESP32",
    formFactor: "DIP-30 (Standard Breadboard Friendly)",
    dimensions: "51.5mm x 28.5mm",
    operatingVoltage: "3.3V Logic",
    inputVoltage: "5V USB / 5V-9V VIN",
    totalGpios: 24,
    adcPins: 15,
    dacPins: 2,
    interfaces: ["2x I2C", "3x UART", "3x SPI", "16x PWM", "10x Capacitive Touch", "CAN 2.0B"],
    strappingInstructions: [
      "GPIO0: Düşük (LOW / GND) yapıldığında ROM Bootloader moduna geçer.",
      "GPIO2: Flaşlama anında boşta veya LOW bırakılmalıdır (dahili LED bağlı).",
      "GPIO12 (MTDI): Varsayılan LOW olmalıdır (Flash voltajını 3.3V seçer).",
      "GPIO15: Varsayılan HIGH / Sessiz log modudur.",
      "EN (Reset): 10uF kondansatör (EN ile GND arasına) otomatik bootloader'ı kararlı hale getirir.",
    ],
    pins: [
      // Left side
      { pinNumber: 1, label: "EN", physicalPosition: "left", color: "strapping", functions: ["Reset", "Chip Enable"], description: "Düşük (LOW) aktif reset" },
      { pinNumber: 2, label: "VP (GPIO36)", physicalPosition: "left", color: "analog", functions: ["ADC1_CH0", "RTC_GPIO0", "S_VP"], description: "Yalnızca Giriş (Input Only)" },
      { pinNumber: 3, label: "VN (GPIO39)", physicalPosition: "left", color: "analog", functions: ["ADC1_CH3", "RTC_GPIO3", "S_VN"], description: "Yalnızca Giriş (Input Only)" },
      { pinNumber: 4, label: "GPIO34", physicalPosition: "left", color: "analog", functions: ["ADC1_CH6", "RTC_GPIO4"], description: "Yalnızca Giriş (Input Only)" },
      { pinNumber: 5, label: "GPIO35", physicalPosition: "left", color: "analog", functions: ["ADC1_CH7", "RTC_GPIO5"], description: "Yalnızca Giriş (Input Only)" },
      { pinNumber: 6, label: "GPIO32", physicalPosition: "left", color: "touch", functions: ["ADC1_CH4", "TOUCH9", "RTC_GPIO9"], description: "ADC + Dokunmatik Pin" },
      { pinNumber: 7, label: "GPIO33", physicalPosition: "left", color: "touch", functions: ["ADC1_CH5", "TOUCH8", "RTC_GPIO8"], description: "ADC + Dokunmatik Pin" },
      { pinNumber: 8, label: "GPIO25", physicalPosition: "left", color: "dac", functions: ["DAC1", "ADC2_CH8", "RTC_GPIO6"], description: "8-bit Gerçek Analog DAC Çıkışı" },
      { pinNumber: 9, label: "GPIO26", physicalPosition: "left", color: "dac", functions: ["DAC2", "ADC2_CH9", "RTC_GPIO7"], description: "8-bit Gerçek Analog DAC Çıkışı" },
      { pinNumber: 10, label: "GPIO27", physicalPosition: "left", color: "touch", functions: ["TOUCH7", "ADC2_CH7", "RTC_GPIO17"], description: "Dokunmatik + ADC" },
      { pinNumber: 11, label: "GPIO14", physicalPosition: "left", color: "comm", functions: ["HSPI_CLK", "TOUCH6", "ADC2_CH6"], description: "SPI Saat / JTAG TMS" },
      { pinNumber: 12, label: "GPIO12", physicalPosition: "left", color: "strapping", isStrappingPin: true, functions: ["HSPI_MISO", "TOUCH5", "MTDI"], description: "Strapping Pin (Flash Voltajı)" },
      { pinNumber: 13, label: "GPIO13", physicalPosition: "left", color: "comm", functions: ["HSPI_MOSI", "TOUCH4", "MTCK"], description: "SPI MOSI / JTAG TCK" },
      { pinNumber: 14, label: "GND", physicalPosition: "left", color: "ground", functions: ["Ground"], description: "0V Toprak Hattı" },
      { pinNumber: 15, label: "VIN (5V)", physicalPosition: "left", color: "power", functions: ["Power In (5V-9V)"], description: "Harici Güç Girişi" },

      // Right side
      { pinNumber: 16, label: "GPIO23", physicalPosition: "right", color: "comm", functions: ["VSPI_MOSI", "SPI_MOSI"], description: "Varsayılan SPI MOSI" },
      { pinNumber: 17, label: "GPIO22", physicalPosition: "right", color: "comm", functions: ["I2C_SCL", "Wire SCL"], description: "Varsayılan I2C Saat Hattı" },
      { pinNumber: 18, label: "GPIO1 (TX0)", physicalPosition: "right", color: "comm", functions: ["UART0_TX", "Serial TX"], description: "Seri Monitör TX Çıkışı" },
      { pinNumber: 19, label: "GPIO3 (RX0)", physicalPosition: "right", color: "comm", functions: ["UART0_RX", "Serial RX"], description: "Seri Monitör RX Girişi" },
      { pinNumber: 20, label: "GPIO21", physicalPosition: "right", color: "comm", functions: ["I2C_SDA", "Wire SDA"], description: "Varsayılan I2C Veri Hattı" },
      { pinNumber: 21, label: "GND", physicalPosition: "right", color: "ground", functions: ["Ground"], description: "0V Toprak Hattı" },
      { pinNumber: 22, label: "GPIO19", physicalPosition: "right", color: "comm", functions: ["VSPI_MISO", "SPI_MISO"], description: "Varsayılan SPI MISO" },
      { pinNumber: 23, label: "GPIO18", physicalPosition: "right", color: "comm", functions: ["VSPI_SCK", "SPI_SCK"], description: "Varsayılan SPI Clock" },
      { pinNumber: 24, label: "GPIO5", physicalPosition: "right", color: "comm", functions: ["VSPI_CS", "SPI_SS"], description: "SPI Chip Select" },
      { pinNumber: 25, label: "GPIO17", physicalPosition: "right", color: "comm", functions: ["UART2_TX"], description: "İkinci Seri Port TX2" },
      { pinNumber: 26, label: "GPIO16", physicalPosition: "right", color: "comm", functions: ["UART2_RX"], description: "İkinci Seri Port RX2" },
      { pinNumber: 27, label: "GPIO4", physicalPosition: "right", color: "touch", functions: ["TOUCH0", "ADC2_CH0"], description: "Dokunmatik 0" },
      { pinNumber: 28, label: "GPIO0", physicalPosition: "right", color: "strapping", isStrappingPin: true, functions: ["BOOT", "ADC2_CH1", "TOUCH1"], description: "BOOT Butonu & Flaşlama Modu" },
      { pinNumber: 29, label: "GPIO2", physicalPosition: "right", color: "strapping", isStrappingPin: true, functions: ["LED_BUILTIN", "ADC2_CH2", "TOUCH2"], description: "Dahili Mavi LED & Boot Strapping" },
      { pinNumber: 30, label: "GPIO15", physicalPosition: "right", color: "strapping", isStrappingPin: true, functions: ["MTDO", "ADC2_CH3", "TOUCH3"], description: "JTAG MTDO & Strapping" },
    ],
  },

  // 2. ESP32-S3 DevKit
  {
    id: "esp32-s3-devkit",
    name: "ESP32-S3 DevKitC-1 (Octal / Dual USB)",
    chip: "ESP32-S3",
    formFactor: "DIP-44 (Dual Type-C / USB-OTG + UART)",
    dimensions: "55.0mm x 28.0mm",
    operatingVoltage: "3.3V Logic",
    inputVoltage: "5V USB / 5V-9V VIN",
    totalGpios: 36,
    adcPins: 20,
    dacPins: 0,
    interfaces: ["USB-OTG Native", "2x I2C", "3x UART", "4x SPI", "AI Vector Engine", "RGB WS2812 LED"],
    strappingInstructions: [
      "GPIO0: LOW çekilirse USB-JTAG/Serial Download Bootloader moduna girer.",
      "GPIO45 (VDD_SPI): 3.3V Octal Flash için kritik strapping pini.",
      "GPIO46: ROM kod çalıştırma modu belirleyicisi (Varsayılan LOW).",
    ],
    pins: [
      { pinNumber: 1, label: "3V3", physicalPosition: "left", color: "power", functions: ["Power Out (3.3V)"], description: "Dahili 3.3V LDO Çıkışı" },
      { pinNumber: 2, label: "GPIO0 (BOOT)", physicalPosition: "left", color: "strapping", isStrappingPin: true, functions: ["BOOT", "RTC_GPIO0"], description: "Flaşlama ve Boot Butonu" },
      { pinNumber: 3, label: "GPIO1", physicalPosition: "left", color: "analog", functions: ["ADC1_CH0", "TOUCH1"], description: "Analog Giriş 0" },
      { pinNumber: 4, label: "GPIO2", physicalPosition: "left", color: "analog", functions: ["ADC1_CH1", "TOUCH2"], description: "Analog Giriş 1" },
      { pinNumber: 5, label: "GPIO3", physicalPosition: "left", color: "analog", functions: ["ADC1_CH2", "TOUCH3"], description: "Analog Giriş 2" },
      { pinNumber: 6, label: "GPIO4", physicalPosition: "left", color: "comm", functions: ["I2C_SDA", "ADC1_CH3"], description: "I2C SDA" },
      { pinNumber: 7, label: "GPIO5", physicalPosition: "left", color: "comm", functions: ["I2C_SCL", "ADC1_CH4"], description: "I2C SCL" },
      { pinNumber: 8, label: "GPIO19", physicalPosition: "right", color: "comm", functions: ["USB_D-", "JTAG_D-"], description: "Yerel USB D- Hattı" },
      { pinNumber: 9, label: "GPIO20", physicalPosition: "right", color: "comm", functions: ["USB_D+", "JTAG_D+"], description: "Yerel USB D+ Hattı" },
      { pinNumber: 10, label: "GPIO43", physicalPosition: "right", color: "comm", functions: ["U0TXD"], description: "UART0 TX" },
      { pinNumber: 11, label: "GPIO44", physicalPosition: "right", color: "comm", functions: ["U0RXD"], description: "UART0 RX" },
      { pinNumber: 12, label: "GND", physicalPosition: "right", color: "ground", functions: ["Ground"], description: "Toprak" },
      { pinNumber: 13, label: "5V", physicalPosition: "right", color: "power", functions: ["USB Power (5V)"], description: "5V Giriş / Çıkış" },
    ],
  },

  // 3. Arduino Uno R3
  {
    id: "arduino-uno-r3",
    name: "Arduino Uno R3 (ATmega328P 16MHz)",
    chip: "AVR-ATmega328P",
    formFactor: "Standard Arduino Shield Form Factor",
    dimensions: "68.6mm x 53.4mm",
    operatingVoltage: "5.0V Logic",
    inputVoltage: "7V-12V Barrel Jack / 5V USB-B",
    totalGpios: 14,
    adcPins: 6,
    dacPins: 0,
    interfaces: ["1x UART (115200)", "1x SPI", "1x I2C (A4/A5)", "6x Hardware PWM (3,5,6,9,10,11)"],
    strappingInstructions: [
      "RESET pini 100nF kondansatör ile USB-Serial dönüştürücünün DTR pinine bağlıdır.",
      "Optiboot bootloader her reset sonrası 200ms boyunca STK500v1 komutlarını bekler.",
    ],
    pins: [
      { pinNumber: "D0", label: "RX <- 0", physicalPosition: "left", color: "comm", functions: ["UART_RX"], description: "Seri Port Alıcı" },
      { pinNumber: "D1", label: "TX -> 1", physicalPosition: "left", color: "comm", functions: ["UART_TX"], description: "Seri Port Verici" },
      { pinNumber: "D2", label: "Digital 2", physicalPosition: "left", color: "gpio", functions: ["INT0"], description: "Harici Kesme 0" },
      { pinNumber: "D3", label: "Digital 3 ~", physicalPosition: "left", color: "gpio", functions: ["PWM", "INT1"], description: "8-bit Donanımsal PWM" },
      { pinNumber: "D13", label: "Digital 13", physicalPosition: "right", color: "comm", functions: ["SCK", "LED_BUILTIN"], description: "Dahili LED & SPI Saat" },
      { pinNumber: "A4", label: "Analog 4 (SDA)", physicalPosition: "right", color: "comm", functions: ["ADC4", "I2C_SDA"], description: "Analog Giriş & I2C Veri" },
      { pinNumber: "A5", label: "Analog 5 (SCL)", physicalPosition: "right", color: "comm", functions: ["ADC5", "I2C_SCL"], description: "Analog Giriş & I2C Saat" },
      { pinNumber: "5V", label: "5V Power", physicalPosition: "right", color: "power", functions: ["5V Regulated"], description: "5V Besleme" },
      { pinNumber: "GND", label: "Ground", physicalPosition: "right", color: "ground", functions: ["0V"], description: "Toprak" },
    ],
  },

  // 4. Raspberry Pi Pico (RP2040)
  {
    id: "rp2040-pico",
    name: "Raspberry Pi Pico (RP2040 Dual ARM Cortex-M0+)",
    chip: "RP2040",
    formFactor: "Castellated 40-Pin DIP Module",
    dimensions: "51.0mm x 21.0mm",
    operatingVoltage: "3.3V Logic",
    inputVoltage: "1.8V-5.5V VSYS / 5V VBUS",
    totalGpios: 26,
    adcPins: 3,
    dacPins: 0,
    interfaces: ["2x SPI", "2x I2C", "2x UART", "16x PWM", "8x Programmable IO (PIO) State Machines"],
    strappingInstructions: [
      "BOOTSEL: Butona basılı tutularak USB kablosu takıldığında UF2 Bootloader disk moduna (RPI-RP2) geçer.",
      "1200 Baud Dokunuşu: Seri port 1200 baud ile açılıp kapatıldığında kart otomatik bootloader'a döner.",
    ],
    pins: [
      { pinNumber: 1, label: "GP0", physicalPosition: "left", color: "comm", functions: ["UART0_TX", "I2C0_SDA"], description: "UART0 TX / I2C0 SDA" },
      { pinNumber: 2, label: "GP1", physicalPosition: "left", color: "comm", functions: ["UART0_RX", "I2C0_SCL"], description: "UART0 RX / I2C0 SCL" },
      { pinNumber: 3, label: "GND", physicalPosition: "left", color: "ground", functions: ["Ground"], description: "Toprak" },
      { pinNumber: 4, label: "GP2", physicalPosition: "left", color: "gpio", functions: ["SPI0_SCK", "I2C1_SDA"], description: "SPI0 Clock" },
      { pinNumber: 36, label: "3V3(OUT)", physicalPosition: "right", color: "power", functions: ["3.3V Power Out"], description: "Dahili 3.3V Çıkışı" },
      { pinNumber: 39, label: "VSYS", physicalPosition: "right", color: "power", functions: ["Power In (1.8V-5.5V)"], description: "Sistem Besleme Girişi" },
      { pinNumber: 40, label: "VBUS", physicalPosition: "right", color: "power", functions: ["5V USB Power"], description: "USB 5V Hattı" },
    ],
  },

  // 5. STM32 BluePill (STM32F103C8T6)
  {
    id: "stm32-bluepill",
    name: "STM32F103C8T6 'BluePill' (ARM Cortex-M3 72MHz)",
    chip: "STM32F103",
    formFactor: "DIP-40 Breadboard Module",
    dimensions: "53.3mm x 22.9mm",
    operatingVoltage: "3.3V Logic (Bazı pinler 5V Tolerant)",
    inputVoltage: "5V USB / 3.3V Pin",
    totalGpios: 32,
    adcPins: 10,
    dacPins: 0,
    interfaces: ["2x I2C", "3x USART", "2x SPI", "USB 2.0 Full Speed", "CAN 2.0B", "DMA Controller"],
    strappingInstructions: [
      "BOOT0 Jumper: 1 (3.3V) konumuna getirilip RESET basıldığında Dahili USART Sistem Bootloader moduna geçer.",
      "BOOT0 Jumper: 0 (GND) konumunda Flash bellekteki kullanıcı yazılımını çalıştırır.",
      "BOOT1 Jumper: Varsayılan 0 (GND) konumunda olmalıdır.",
    ],
    pins: [
      { pinNumber: "PA9", label: "PA9 (USART1_TX)", physicalPosition: "left", color: "comm", functions: ["USART1_TX", "PWM"], description: "AN3155 Flaşlama TX Pini" },
      { pinNumber: "PA10", label: "PA10 (USART1_RX)", physicalPosition: "left", color: "comm", functions: ["USART1_RX", "PWM"], description: "AN3155 Flaşlama RX Pini" },
      { pinNumber: "PA11", label: "PA11 (USB_DM)", physicalPosition: "left", color: "comm", functions: ["USB_D-", "CAN_RX"], description: "USB D- Hattı" },
      { pinNumber: "PA12", label: "PA12 (USB_DP)", physicalPosition: "left", color: "comm", functions: ["USB_D+", "CAN_TX"], description: "USB D+ Hattı" },
      { pinNumber: "PC13", label: "PC13 (LED)", physicalPosition: "right", color: "gpio", functions: ["LED_BUILTIN", "Tamper"], description: "Dahili Yeşil LED (Active LOW)" },
      { pinNumber: "3V3", label: "3.3V Power", physicalPosition: "right", color: "power", functions: ["3.3V VDD"], description: "3.3V Besleme" },
      { pinNumber: "GND", label: "Ground", physicalPosition: "right", color: "ground", functions: ["0V VSS"], description: "Toprak" },
    ],
  },
];
